# Generated by Django 4.0.4 on 2022-05-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0003_customer_delete_customermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileViewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.FileField(upload_to='files/')),
                ('file_name', models.CharField(max_length=100)),
                ('file_content', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
