# Generated by Django 4.0.4 on 2022-05-14 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0004_fileviewer_alter_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileviewer',
            name='file_content',
        ),
        migrations.RemoveField(
            model_name='fileviewer',
            name='file_name',
        ),
    ]
